# Generated by Django 4.2.9 on 2024-01-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_Blog', '0002_usuariopersonalizado_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
    ]
